services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: fks-api:dev
    volumes:
      - ./src:/app/src:ro
      - ./shared:/app/shared:ro
    environment:
      APP_ENV: development
      API_SERVICE_NAME: FKS API Dev
      OLLAMA_AUTOPULL: "0"
    command: uvicorn fks_api.fastapi_main:app --host 0.0.0.0 --port 8000 --reload
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: fks-api:dev
    environment:
      REDIS_URL: redis://redis:6379/0
      APP_ENV: development
    command: celery -A app.celery worker --loglevel=info --concurrency=1
    depends_on:
      - redis
  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    image: fks-api:dev
    environment:
      REDIS_URL: redis://redis:6379/0
      APP_ENV: development
    command: celery -A app.celery beat --loglevel=info
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
