services:
  fks_api:
    container_name: fks_api
    build:
      context: .
      dockerfile: shared/shared_docker/templates/Dockerfile.python
      args:
        PYTHON_VERSION: "3.11"
        BUILD_PACKAGES: "build-essential gcc libpq-dev"
    env_file:
      - ./.env
    environment:
      APP_ENV: development
      APP_MODULE: fastapi_main:app
      SERVICE_PORT: 8000
      SERVICE_TYPE: api
    volumes:
      - ./src:/app/src:ro
      - ./shared/shared_scripts:/app/shared/shared_scripts:ro
    ports:
      - "8000:8000"
    networks: [fks_net]
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import socket,os; s=socket.socket(); s.settimeout(2); s.connect(('127.0.0.1', int(os.environ.get('SERVICE_PORT',8000)))); s.close()\" || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s

networks:
  fks_net:
    name: fks_net