name: Codebase Analysis (fks_api)

on:
  push:
    branches: [ main, master ]
    paths:
      - 'src/**'
      - '.github/workflows/codebase-analysis.yml'
  schedule:
    - cron: '17 3 * * *'
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Count TODO/FIXME
        run: |
          set -e
          todo=$(grep -R --exclude-dir .git -c "TODO" src || true | awk -F: '{s+=$2} END{print s+0}')
          fixme=$(grep -R --exclude-dir .git -c "FIXME" src || true | awk -F: '{s+=$2} END{print s+0}')
          files=$(find src -type f -name '*.py' | wc -l | tr -d ' ')
          echo "{\n  \"todo\": $todo,\n  \"fixme\": $fixme,\n  \"files_scanned\": $files\n}" > analysis.json
          cat analysis.json
      - uses: actions/upload-artifact@v4
        with:
          name: codebase-analysis
          path: analysis.json
      - name: Summary
        run: |
          echo "### Codebase Metrics" >> $GITHUB_STEP_SUMMARY
          echo "* TODO: $(jq '.todo' analysis.json)" >> $GITHUB_STEP_SUMMARY || true
          echo "* FIXME: $(jq '.fixme' analysis.json)" >> $GITHUB_STEP_SUMMARY || true
          echo "* Files Scanned: $(jq '.files_scanned' analysis.json)" >> $GITHUB_STEP_SUMMARY || true
