name: Build fks_api Image (standalone)

on:
  push:
    branches: [ main, master ]
    paths:
      - 'Dockerfile.simple'
      - 'requirements*.txt'
      - 'src/**'
      - '.github/workflows/docker-images-build.yml'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: fks_api
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: (Optional) Login DockerHub
        if: ${{ secrets.DOCKERHUB_USERNAME && secrets.DOCKERHUB_TOKEN }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME != '' && format('{0}/{1}', secrets.DOCKERHUB_USERNAME, env.IMAGE_NAME) || format('local/{0}', env.IMAGE_NAME) }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha
            type=raw,value=latest

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.simple
          push: ${{ secrets.DOCKERHUB_USERNAME && secrets.DOCKERHUB_TOKEN }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            INSTALL_DEV=true

      - name: Smoke Test
        run: |
          docker run -d --rm -p 8000:8000 --name fks_api_smoke ${{ steps.meta.outputs.tags }}
          for i in {1..20}; do sleep 2; if curl -sf localhost:8000/health >/dev/null; then echo OK; break; fi; if [ $i -eq 20 ]; then echo FAIL; docker logs fks_api_smoke; exit 1; fi; done
          docker stop fks_api_smoke
