name: Compose Validation (fks_api)

on:
  pull_request:
    paths:
      - 'docker-compose*.yml'
      - '.github/workflows/compose-aggregate-check.yml'
  push:
    branches: [ main, master ]
    paths:
      - 'docker-compose*.yml'
      - '.github/workflows/compose-aggregate-check.yml'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: docker-compose config
        run: |
          if ls docker-compose*.yml 1>/dev/null 2>&1; then
            for f in docker-compose*.yml; do
              echo "Validating $f"; docker compose -f "$f" config >/dev/null || exit 1;
            done
          else
            echo '::warning::No compose files found'
          fi
      - name: Check service fks_api present
        run: |
          if grep -q '^  fks_api:' docker-compose.yml; then echo 'fks_api service found'; else echo '::error::fks_api service missing in docker-compose.yml'; exit 1; fi
      - name: Check healthcheck
        run: |
          if grep -q 'healthcheck' docker-compose.yml; then echo 'Healthcheck present'; else echo '::warning::No healthcheck in docker-compose.yml'; fi
