name: fks_api CI

on:
  push:
    branches: [ main, master ]
    paths:
      - 'src/**'
      - 'pyproject.toml'
      - 'requirements*.txt'
      - 'Dockerfile'
      - '.github/workflows/fks_api-ci.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'pyproject.toml'
      - 'requirements*.txt'
      - 'Dockerfile'
      - '.github/workflows/fks_api-ci.yml'
  workflow_dispatch: {}

jobs:
  test:
    name: Unit Tests (Python)
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'  # Ensure shared_python submodule is checked out
          
      - name: Verify shared_python dependency
        run: |
          if [ ! -d "shared_python" ] && [ -f ".gitmodules" ]; then
            echo "shared_python not found but .gitmodules exists, attempting to initialize submodules"
            git submodule update --init --recursive
          fi
          ls -la shared_python/ || echo "shared_python directory not available"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.11'
            cache: 'pip'
            cache-dependency-path: |
              requirements.txt
              requirements.dev.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements.dev.txt
          # Note: shared_python is added to PYTHONPATH in test steps instead of installing as editable package

      - name: Validate imports
        env:
          PYTHONPATH: ${{ github.workspace }}/src:${{ github.workspace }}/shared_python
        run: python validate_imports.py

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}/src:${{ github.workspace }}/shared_python
        run: pytest src/tests/ -q --maxfail=1 --disable-warnings --color=yes

      - name: Upload test results (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-cache
          path: .pytest_cache
          if-no-files-found: ignore

  docker-build:
    name: Docker Build (fks_api)
    runs-on: ubuntu-latest
    needs: test
    timeout-minutes: 20
    permissions:
      contents: read
      packages: write
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'  # Ensure shared_python submodule is checked out

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: (Optional) Log in to DockerHub
        if: ${{ env.DOCKER_USERNAME != '' && env.DOCKER_TOKEN != '' }}
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_USERNAME != '' && format('{0}/fks_api', env.DOCKER_USERNAME) || 'local/fks_api' }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha
            type=raw,value=latest

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.simple
          push: ${{ env.DOCKER_USERNAME != '' && env.DOCKER_TOKEN != '' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            SERVICE_RUNTIME=python
            SERVICE_TYPE=api
            BUILD_TYPE=cpu

      - name: Run container smoke test
        run: |
          # Get the first tag from the metadata output
          IMAGE_TAG=$(echo "${{ steps.meta.outputs.tags }}" | head -n1)
          docker run -d --rm -p 8080:8000 --name fks_api_test "$IMAGE_TAG"
          echo 'Waiting for health endpoint...'
          for i in {1..20}; do
            sleep 2
            if curl -sf http://localhost:8080/health > /dev/null; then
              echo 'Service responded to /health';
              curl -s http://localhost:8080/health | head -c 500;
              break;
            fi
            if [ $i -eq 20 ]; then echo 'Service failed to become healthy'; docker logs fks_api_test || true; exit 1; fi
          done
          docker logs fks_api_test | tail -n 50 || true
          docker stop fks_api_test

      - name: Export image artifact (no push scenario)
        if: ${{ env.DOCKER_USERNAME == '' || env.DOCKER_TOKEN == '' }}
        run: |
          # Get the first tag from the metadata output
          IMAGE_TAG=$(echo "${{ steps.meta.outputs.tags }}" | head -n1)
          docker save "$IMAGE_TAG" | gzip > fks_api-image.tar.gz
        
      - name: Upload image artifact
        if: ${{ env.DOCKER_USERNAME == '' || env.DOCKER_TOKEN == '' }}
        uses: actions/upload-artifact@v4
        with:
          name: fks_api-image
          path: fks_api-image.tar.gz
